import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Typography,
} from "@mui/material";

import InfoScreen from "./screens/info.png";
import BiasScreen from "./screens/bias.png";
import SimilarScreen from "./screens/similar.png";
import FallaciesScreen from "./screens/fallacies.png";

import { useEffect, useRef, useState } from "react";

const Panel2 = () => {
  const [expanded, setExpanded] = useState<number>(0);
  const ref = useRef<HTMLDivElement | null>(null);
  const interValRef = useRef<number>(0);

  const isExpanded = (idx: number) => expanded === idx;

  useEffect(() => {
    if (!ref || !ref.current) return;

    clearInterval(interValRef.current);
    interValRef.current = setInterval(() => {
      if (!ref || !ref.current) return;

      const divScrollTop = ref.current.scrollHeight - ref.current.clientHeight / 2;
      const divFourthHeight = ref.current.clientHeight / 5;
      const newVal = Math.floor((window.scrollY - divScrollTop) / divFourthHeight) + 2;
      const newValClamp = Math.max(0, Math.min(3, newVal));
      if (newValClamp != expanded || newValClamp === 0) setExpanded(newValClamp)
    }, 100);
  }, [ref, expanded]);

  const PartComponent = ({
    idx,
    summary,
    description,
  }: {
    idx: number;
    summary: string;
    description: string;
  }) => {
    return (
      <Accordion
        expanded={isExpanded(idx)}
        className="mb-4 mt-0"
      >
        <AccordionSummary
          className="bg-slate-100"
        >
          <Typography className="text-xl">{summary}</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>{description}</Typography>
        </AccordionDetails>
      </Accordion>
    );
  };

  const images = [InfoScreen, BiasScreen, SimilarScreen, FallaciesScreen];

  return (
    <div className="flex justify-center">
      <div className="h-[calc(100vh*4)] w-full max-w-[95rem] flex" ref={ref}>
        <div className="w-2/5 h-full p-8 flex justify-center relative pt-[300px] tall:2xl:pt-[425px]">
          <img
            src={images[expanded]}
            className="w-[400px] h-[500px] tall:2xl:w-[500px] tall:2xl:h-[625px] sticky top-1/2 -translate-y-1/2 border-[12px] tall:2xl:border-[24px] border-solid border-[rgb(242,247,252)] rounded-lg"
          />
        </div>
        <div
          className="w-3/5 h-full"
          style={{
            paddingTop:
              "calc(max(calc((100vh - 200px) / 2), 35rem / 2) + 50px)",
          }}
        >
          <div className="p-8 sticky top-1/2 -translate-y-1/2 rounded-xl h-[calc(100vh-200px)] min-h-[35rem] flex flex-col justify-center">
            <Typography className="text-4xl font-bold text-center mb-8">
              How does it work?
            </Typography>

            <PartComponent
              idx={0}
              summary="1. General Info"
              description="After completing its analysis, the first tab shows the article's title as well as a clear and concise summary of the article. One of the key features on this tab include historical reliability and bias ratings of the source, obtained from a reputable third-party, Ad Fontes Media."
            />

            <PartComponent
              idx={1}
              summary="2. Bias Analysis"
              description="The second tab shows the article's bias, generated by GPT-4, presenting both a specific bias rating and the detailed reasoning behind this rating. The use of an LLM allows for a dissection of various elements such as word choice, framing of arguments, inclusion or exclusion of specific facts or viewpoints, as well as a clear explanation for the bias rating assigned."
            />

            <PartComponent
              idx={2}
              summary="3. Similar Articles"
              description="The third tab finds articles with the same topic but from different sources and with varying viewpoints. This feature helps give differing viewpoints and sources on the same topic."
            />

            <PartComponent
              idx={3}
              summary="4. Fallacy Detection"
              description="Finally, the fourth tab is dedicated to identifying and explaining any logical fallacies found within the original article. Logical fallacies are errors in reasoning that undermine the logic of an argument, and can often be difficult to spot and understand. They are usually signs of misleading information or illogical arguments presented in the article."
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Panel2;
